#!/usr/bin/env python3
"""
万得数据同步配置
包含所有78个ticker的配置信息
"""

# 万得数据配置列表
WIND_CONFIG = [
    # FX - 外汇汇率 (4条) -> fx_rates
    {'分类': 'fx', 'tickers': 'M0000185', 'source': 'wind', 'function': 'edb', 'start_date': '2005-12-31', 'fields': 'fx', 'options': None, 'table_name': 'qis_fx_quote_info', 'PRI': 'trade_date,asset_id', 'swifquant_asset_id': 'CNY'},
    {'分类': 'fx', 'tickers': 'M0000186', 'source': 'wind', 'function': 'edb', 'start_date': '2005-12-31', 'fields': 'fx', 'options': None, 'table_name': 'qis_fx_quote_info', 'PRI': 'trade_date,asset_id', 'swifquant_asset_id': 'EUR'},
    {'分类': 'fx', 'tickers': 'M0000187', 'source': 'wind', 'function': 'edb', 'start_date': '2005-12-31', 'fields': 'fx', 'options': None, 'table_name': 'qis_fx_quote_info', 'PRI': 'trade_date,asset_id', 'swifquant_asset_id': 'JPY'},
    {'分类': 'fx', 'tickers': 'M0000188', 'source': 'wind', 'function': 'edb', 'start_date': '2005-12-31', 'fields': 'fx', 'options': None, 'table_name': 'qis_fx_quote_info', 'PRI': 'trade_date,asset_id', 'swifquant_asset_id': 'HKD'},

    # Market Data - 市场数据 (17条) -> macro_indicators
    {'分类': 'r007', 'tickers': 'M0041653', 'source': 'wind', 'function': 'edb', 'start_date': '1999-01-04', 'fields': 'r007', 'options': None, 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'r007'},
    {'分类': '10yrates', 'tickers': 'B2559386', 'source': 'wind', 'function': 'edb', 'start_date': '2000-01-03', 'fields': 'rates', 'options': 'Fill=Previous', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '10y_rate_cn'},
    {'分类': '10yrates', 'tickers': 'G0000891', 'source': 'wind', 'function': 'edb', 'start_date': '2000-01-03', 'fields': 'rates', 'options': 'Fill=Previous', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '10y_rate_us'},
    {'分类': '10yrates', 'tickers': 'G1235664', 'source': 'wind', 'function': 'edb', 'start_date': '2000-01-03', 'fields': 'rates', 'options': 'Fill=Previous', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '10y_rate_de'},
    {'分类': '10yrates', 'tickers': 'G8322945', 'source': 'wind', 'function': 'edb', 'start_date': '2000-01-03', 'fields': 'rates', 'options': 'Fill=Previous', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '10y_rate_jp'},
    {'分类': '10yrates', 'tickers': 'M0325687', 'source': 'wind', 'function': 'edb', 'start_date': '2000-01-03', 'fields': 'rates', 'options': 'Fill=Previous', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '10y_rate_uk'},
    {'分类': '10yrates', 'tickers': 'S0059749', 'source': 'wind', 'function': 'edb', 'start_date': '2000-01-03', 'fields': 'rates', 'options': 'Fill=Previous', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '10y_rate_fr'},
    {'分类': 'dividend_yield', 'tickers': '000300.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_300'},
    {'分类': 'dividend_yield', 'tickers': '000688.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_kc50'},
    {'分类': 'dividend_yield', 'tickers': '000905.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_500'},
    {'分类': 'dividend_yield', 'tickers': '000906.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_800'},
    {'分类': 'dividend_yield', 'tickers': 'DJI.GI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_djia'},
    {'分类': 'dividend_yield', 'tickers': 'GDAXI.GI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_dax'},
    {'分类': 'dividend_yield', 'tickers': 'HSCEI.HI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_hscei'},
    {'分类': 'dividend_yield', 'tickers': 'N225.GI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_nikkei'},
    {'分类': 'dividend_yield', 'tickers': 'NDX.GI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_nasdaq'},
    {'分类': 'dividend_yield', 'tickers': 'SPX.GI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'dividendyield2', 'options': 'Days=Weekdays', 'table_name': 'qis_market_data', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'dividend_yield_sp500'},

    # Underlying ETF - ETF基金 (17条) -> prices_stock
    {'分类': 'underlying_etf', 'tickers': '0JGN.L', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'PriceAdj=F;TradingCalendar=NYSE', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '罗素2000ETF'},
    {'分类': 'underlying_etf', 'tickers': '588000.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '科创50ETF'},
    {'分类': 'underlying_etf', 'tickers': 'INDA.BAT', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'PriceAdj=F;TradingCalendar=NYSE', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'MSCI印度ETF'},
    {'分类': 'underlying_etf', 'tickers': '159732.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '消费电子ETF'},
    {'分类': 'underlying_etf', 'tickers': '159755.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '新能源ETF'},
    {'分类': 'underlying_etf', 'tickers': '159852.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '地产ETF'},
    {'分类': 'underlying_etf', 'tickers': '159985.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '粮食ETF'},
    {'分类': 'underlying_etf', 'tickers': '159992.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '创新药ETF'},
    {'分类': 'underlying_etf', 'tickers': '159995.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '半导体ETF'},
    {'分类': 'underlying_etf', 'tickers': '511380.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '可转债ETF'},
    {'分类': 'underlying_etf', 'tickers': '512400.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '有色金属ETF'},
    {'分类': 'underlying_etf', 'tickers': '512660.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '军工ETF'},
    {'分类': 'underlying_etf', 'tickers': '512890.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '红利低波ETF'},
    {'分类': 'underlying_etf', 'tickers': '515790.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '光伏ETF'},
    {'分类': 'underlying_etf', 'tickers': '515980.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '人工智能ETF'},
    {'分类': 'underlying_etf', 'tickers': '562500.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '机器人ETF'},
    {'分类': 'underlying_etf', 'tickers': '159915.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': 'priceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '创业板ETF'},

    # Underlying OTC - 场外基金 (3条) -> prices_stock
    {'分类': 'underlying_otc', 'tickers': '007994.OF', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'NAV_adj', 'options': 'PriceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证500指数'},
    {'分类': 'underlying_otc', 'tickers': '110026.OF', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'NAV_adj', 'options': 'PriceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '110026'},
    {'分类': 'underlying_otc', 'tickers': '501018.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'NAV_adj', 'options': 'PriceAdj=F', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '南方原油'},

    # Underlying Index - 底层指数 (37条) -> prices_index
    {'分类': 'underlying_index', 'tickers': 'CBA00642.CS', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中债5-7年国债总净价指数'},
    {'分类': 'underlying_index', 'tickers': 'CBA00652.CS', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中债7-10年国债总净价指数'},
    {'分类': 'underlying_index', 'tickers': '000140.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '上证5年国债指数'},
    {'分类': 'underlying_index', 'tickers': '000300.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '沪深300指数'},
    {'分类': 'underlying_index', 'tickers': '000688.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '科创50指数'},
    {'分类': 'underlying_index', 'tickers': '000852.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证1000指数'},
    {'分类': 'underlying_index', 'tickers': '000905.SH', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证500指数'},
    {'分类': 'underlying_index', 'tickers': '100001.CCI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证商品期货指数'},
    {'分类': 'underlying_index', 'tickers': '399006.SZ', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '创业板指数'},
    {'分类': 'underlying_index', 'tickers': '931078.CSI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证转债指数'},
    {'分类': 'underlying_index', 'tickers': '932265CNY010.CSI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证香港创新药全收益指数'},
    {'分类': 'underlying_index', 'tickers': '950084.CSI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证2年债券指数'},
    {'分类': 'underlying_index', 'tickers': 'CBA00621.CS', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中债1-3年国债总财富指数'},
    {'分类': 'underlying_index', 'tickers': 'CBA00622.CS', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中债1-3年国债总净价指数'},
    {'分类': 'underlying_index', 'tickers': 'CBA00662.CS', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中债-10年以上国债总净价指数'},
    {'分类': 'underlying_index', 'tickers': 'CBA11421.CS', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'AA+企业债'},
    {'分类': 'underlying_index', 'tickers': 'CBA21802.CS', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中债-30年国债总净价指数'},
    {'分类': 'underlying_index', 'tickers': 'CISAGRIER.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得中国农产品'},
    {'分类': 'underlying_index', 'tickers': 'CISCHER.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得中国能化商品'},
    {'分类': 'underlying_index', 'tickers': 'CISES.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得标普500'},
    {'分类': 'underlying_index', 'tickers': 'CISFEER.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得中国有色商品'},
    {'分类': 'underlying_index', 'tickers': 'CISFGBL.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得德国10年国债'},
    {'分类': 'underlying_index', 'tickers': 'CISGC.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得COMEX黄金'},
    {'分类': 'underlying_index', 'tickers': 'CISHG.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得COMEX铜'},
    {'分类': 'underlying_index', 'tickers': 'CISJGB.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得日本10年国债'},
    {'分类': 'underlying_index', 'tickers': 'CISJNM.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得日经225'},
    {'分类': 'underlying_index', 'tickers': 'CISLCO.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得布伦特原油'},
    {'分类': 'underlying_index', 'tickers': 'CISNQ.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得纳斯达克100'},
    {'分类': 'underlying_index', 'tickers': 'CISSTXE.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得STOXX50'},
    {'分类': 'underlying_index', 'tickers': 'CISTU2.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得土耳其2年国债'},
    {'分类': 'underlying_index', 'tickers': 'CISTY2.WI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '万得土耳其10年国债'},
    {'分类': 'underlying_index', 'tickers': 'DCESMFI.DCE', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '大连铁矿石期货价格指数'},
    {'分类': 'underlying_index', 'tickers': 'H11077', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': 'H11077'},
    {'分类': 'underlying_index', 'tickers': 'H20269.CSI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证香港创新药全收益指数'},
    {'分类': 'underlying_index', 'tickers': 'H30269.CSI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '中证香港创新药指数'},
    {'分类': 'underlying_index', 'tickers': 'RTY.GI', 'source': 'wind', 'function': 'wsd', 'start_date': '2000-01-03', 'fields': 'close', 'options': None, 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '罗素2000指数'},
    {'分类': 'underlying_index', 'tickers': 'HSI.HI', 'source': 'wind', 'function': 'wsd', 'start_date': '1964-07-31', 'fields': 'close', 'options': 'PriceAdj=F;TradingCalendar=HKEX', 'table_name': 'qis_underlying_quote_info', 'PRI': 'trade_date,asset_id,fields', 'swifquant_asset_id': '恒生指数'},
]


def get_config_df():
    """返回配置DataFrame"""
    import pandas as pd
    return pd.DataFrame(WIND_CONFIG)
